### ISSUE TITLE
Wochen-/Monatsdiagramm: Auswertung in TRIMP/JD-Intensität

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1032]
**Reported by laufhannes on 25 Nov 44177478 02:14 UTC**
Evtl. im Statistik-Plugin:
Balkendiagramm mit der Summe an TRIMP- oder JD-Trainingspunkten

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1750

**Comment by grzeg1** [comment]
Cool. A few small things:
- [ ] title says "Weekly KM" - should probably say weekly chart because it's no longer just KM
- [ ] in my old 1.5 modified version I also have last 26 weeks average drawn (whatever is used for basic endurance) so it would be nice
- [ ] labels at the bottom should be in time units - hard to say what 20 means, May '14 would look better
- [ ] it's hard to find out just how many km total you've done on weeks with competitions - it'd be probably hard to implement it on 'by type' analysis, but maybe an analysis without type could be added?

**Comment by laufhannes** [comment]
**Title**: For sports without distance it's currently 'Hours of training'. But I agree, 'Monthly/Weekly chart' sounds better.

**Average**: Probably only for running, right? And only for 'Last 12 months' or for al periods? Guess it should be optional as not everyone likes/trusts our basic endurance value. Maybe we could just add a checkbox to show/hide relation to basic endurance, including a note that it's the average of 26 weeks (and not everything displayed) and another line for the calculated goal.

**Labels**: I'll change it to display months for all weeks containing the first day of a month.

**Tooltips**: I'll do that.

**Comment by grzeg1** [comment]
I think last 26 weeks (or whetever BE time is) average shouldn't hurt anyone - it will just be a line (trying to avoid too many unnecessary options which once implemented need to be tested and supported). I did it because for me it's a reference to how much I've been training lately in comparison to the previous periods.


Question: calculated goal: where does it come from?

**Comment by laufhannes** [comment]
From basic endurance: (derived by looking at some marathon training plans)
```php
public function getTargetWeekKm() {
	return pow(max($this->VDOT, 10), 1.135);
}
```

**Comment by laufhannes** [comment]
Todo:
 - show value instead of '*'
 - note: 'Goal and average are based on basic endurance calculations.'
 - color different to grid
 - reposition annotations
 - for all periods (?)
