### ISSUE TITLE
Section: Overview - Felder konfigurierbar machen

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1071]
**Reported by laufhannes on 21 May 44431211 13:29 UTC**
Bisher ist fest vorgegeben, welche Felder angezeigt werden knnen.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1824

**Comment by mipapo** [comment]
@laufhannes  Do you remember what this was about?

**Comment by laufhannes** [comment]
The first line of the activity view has always the same fields, e.g. vo2max even if that activity is not running. This issue was originally meant to let the athlete choose which fields to show. But I guess we can close this, as we will have a look at all this stuff when working on a new interface for the activity view.
