### ISSUE TITLE
Track data and import precision need increasing

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1189]
We need higher precision for track data.
Example: running at 5:00/km => 3.33 m/sec
When storing distance points (km) with 3-digit precision => 3 m/sec => pace shown 5:33 

For importers like GPX where we calculate distance incrementally there is error propagation present. So with 3 digit precision mean error=0.25m, an hour of running (3600 sec) can give 900m error.

**Comment by laufhannes** [comment]
Will 4 digits be enough? And I guess it's enough to store the values temporarily for the import of the gpx file, right? I think there is no need to store this precision in the database.

For displaying pace data on the map it's probably better to use the [PaceSmoother](https://github.com/Runalyze/Runalyze/blob/master/inc/core/Calculation/Activity/PaceSmoother.php) anyway instead of calculating highly inaccurate values with higher precision.

**Comment by grzeg1** [comment]
Even with smoothing there should be 4 or 5 digits. 4 better than 3;)
Maybe there's a way to store these values in a more effective way then just strings. Then precision wouldn't be a problem.
Yes, I also thought about storing values temporarily.
With higher precision values displayed seem pretty ok.

**Comment by grzeg1** [comment]
Idea: track data could be stored as JSON. For arrays starting with 0 index it's almost the same as current format - just brackets at ends and commas instead of pipes.
So it could be 
$db_distance=json_encode($distance_arr);
May be also quicker (needs checking).

**Comment by laufhannes** [comment]
For storing with higher precision in database: I'm currently not sure at which points we actually use the distance array to recalculate something so that we need higher precision.
 - pace plot: simply plots pace array (smoothing is done by flot if requested)
 - pace zones: smoothing is done by `PaceSmoother`

My guess for performance: `ex/implode` is faster than `json_en/decode` and that is faster than `(un)serialize`. For length it's the same order (but the difference between explode and json is negligible).

For having less bytes in database we could think about `base64_de/encode` or some binary representation (so far, I did not find a ready-to-go solution) and check whether the time required for decoding is worth it.

**Comment by grzeg1** [comment]
Distances are used to create pace array. They may come from a footpod and will be different than calculated from GPS.
There's also an export option in Runalyze. I was wondering the other day why exported data look different than imported. I guess this is partly because lack of precision.
IMO when storing data with 1 second time precision, distances should be stored with equivalent precision (at least 1/10 of a meter to get a reasonable speed/pace value).
If disk space is a concern the better way would be to get rid of pace array and increase precision for distance.

Now the other part: I forgot about ex/implode. Thought it was done in a loop.
To save space MySQL lets compress long fields (row_type=COMPRESSED). Also
there is gzcompress function in PHP which is equivalent to MySQL COMPRESS so
it's easy to manipulate data. Compresses to ca. 30% of original data.

**Comment by laufhannes** [comment]
Okay, the export is good point. Fixes for the precision are in your latest pull request, right?

I think the compression gets an own issue and we keep that in mind for later.

**Comment by grzeg1** [comment]
Yes, they are there. But just for GPX and TCX as I don't know much about other formats.

One more idea: precision could be a constant so whenever it needs adjusting it's just one place.
