### ISSUE TITLE
Problem for shape plot: TSB model relies on complete data

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1191]
TSB model relies on complete data:

```php
$this->Fitness[$i] = $T * $lambdaCTL + (1 - $lambdaCTL) * $this->Fitness[$i-1];
$this->Fatigue[$i] = $T * $lambdaATL + (1 - $lambdaATL) * $this->Fatigue[$i-1];
```

Although the impact of older values seems negligible, we can't completely ignore it. One can inspect this problem with outputting exact values for a specific date:

```php
$index = mktime(1,0,0,1,1,2015).'000';
var_dump($CTLs[$index]);
```

This gives `47.69` for 'Last half year' or 'All years', but only `41.54` for '2015'. Currently the query looks back for 42 days
```php
$AddDays = max(Configuration::Trimp()->daysForATL(), Configuration::Trimp()->daysForCTL(), Configuration::Vdot()->days());
```

Using 84 days gives `46.92`, using 126 days gives correct `47.69`.

But if that's our solution (look that many days back) it may be better to fetch data for all days at once and cache the result. Then one could easily add datepickers to select any desired time range.

**Comment by grzeg1** [comment]
With 42 as constant the decayed value is (41/42)^(number of days). This gives ca 0.05 for 126 days (5%) and ca 1% for 192 days.
So data should be 192 days back to get CTL with 1% accuracy or 126 days back to get 5% accuracy.
Getting 192 records of data is not that much so tests are needed if caching is necessary. Maybe some tuning will do (check #1193).

Anyway, I think first of all values show to user should be absolute. Otherwise it means nothing - it may be relative to your max CTL 3 years ago and maybe then you were overtrained. Or when you train more and more you're always at 100%.

**Comment by laufhannes** [comment]
I was confused since my example yielded a correct value for `d = 126`. 
But that's correct, as it's actually `$lambdaCTL = 2 / ($this->CTLn + 1);`, i.e. a decay of `(41/43)^d`

> d =  42:    13.53 %
> d =  84:     1.83 %
> d = 105:    0.67 %
> d = 126:    0.25 %
> d = 147:    0.09 %
> d = 168:    0.03 %

So I think we're good with a factor of 3 (which is used since be3deca49433f846d582d4e3930fdc0da6b8091f).
