### ISSUE TITLE
Activity view: User defined order

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1201]
A completely user-defined view is still in mind but too much work for v2.0. But a test user reported that he's not happy with the new ordering. He wants to have the map at first place.

Quick and dirty idea: A simple configuration value to select the order:
 - laps / trackdata (HR, pace, elevation) / map / additional stuff
 - map / laps / trackdata / stuff
 - map / trackdata / laps / stuff
 - ...

**Comment by grzeg1** [comment]
That's one of the reasons I'm still using my modified 1.5 version ;)
Others are also mainly training-view related, some of them I put in #1133: 
- in v2 everything is bigger and I have to scroll, especially scrolling composite data is frustrating
- in v1.5 pace & hr zones are visible in training view
- my other tweaks for charts (scaling, time data in tooltips)
- my other tweaks for best segments and analysis (#1151)
- Banister model for shape chart (other shape chart things like trimp values are already ported)
If you like some of those I can work on porting to v2.

**Comment by laufhannes** [comment]
As user defined zones and best segments have to be saved in the database, they won't go into v2.0.

For your style proposition: If you provide it in combination with a configuration value so that everyone can switch whenever he wants from one style to another one, that's perect. But I don't know how much work it is to port it that way.

**Comment by grzeg1** [comment]
To clear up: I did not do user-defined zones, but made changes so that Analysis view shows data based on training zones rather than just training averages. In other words you can see e.g. how much time you spent in 80%-90% HR zone in a given month.

I'll see what I can do regarding layout. But it seems a fresh start is needed because of the way components are laid out now.
I'll make a few branches to port my tweaks to v2, you'll then be able to pull what you agree with.

**Comment by grzeg1** [comment]
I made some changes to allow map-first view. Behaves a bit differently depending on if you have composite or separate plots.
I'm not very happy with it, but to do it right a rewrite of current layout is needed. Instead of having rows with predefined components (plots, info, map) we need to have just components and then place them on some kind of a grid.

**Comment by grzeg1** [comment]
Map-first changes merged in #1210
