### ISSUE TITLE
average hear rate per round

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1323]
show average hear rate per round

**Comment by grzeg1** [comment]
I don't understand this one. Round=lap/split or something else?

**Comment by laufhannes** [comment]
Probably. It's done for computed laps but not for manual ones. (Only if manual ones are opened in extra window and distances match)

**Comment by mipapo** [comment]
@grzeg1 Like @laufhannes said. And additional add the average heart rate to the tooltip to the graph

**Comment by grzeg1** [comment]
One of my ideas was adding avg pulse, pace etc to bar chart and completely get rid of laps list, just show link to let user open the window for super-detailed analysis.

**Comment by grzeg1** [comment]
Now it's hard to open the window because the link is buried deep at the bottom of the list you need to scroll.

**Comment by grzeg1** [comment]
@laufhannes what do you think?

**Comment by laufhannes** [comment]
I like the table as I don't have to hover to see the exact time. Maybe one could show lap values below each bar (i.e. transfer table from top-bottom to left-right). - And then it's an easy option to show/hide that table. But I guess that should be left until some general restyling is done.

The link could just be moved to the headline to be directly visible.

**Comment by grzeg1** [comment]
I like the table too. Just most often open the whole table ;) because it has complete info.

Moving link to headline is a good idea. May cause people start opening the full window instead of scrolling ;)

Lap values & bars: it would be nice for like 5 laps, probably not more, because of text width.

Anyway - the issue title is "avg hr per round" - no space in the table on the left. Do we consider moving link to full table up (+ maybe tooltips on bars with avg hr) as a (temporary) solution?

**Comment by laufhannes** [comment]
Yes, that should be enough.

**Comment by mipapo** [comment]
@grzeg1 @laufhannes For the tables round, combined data, Strecke- und Höhenmeter the "More information", "More about..." should go to the title. 
I have the feedback that most users don't see this option, because nobody is scrolling to the end of the table.

**Comment by grzeg1** [comment]
@mipapo that's what we wrote in the comments just above yours ;)

**Comment by mipapo** [comment]
@grzeg1 Good morning to myself... :D
