### ISSUE TITLE
Normal/Expert Mode for settings

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1325]
Think we'll see this in May (Usability Testing), but a big problem is that new users see too much settings. 
So there should be a switchbutton for normal and expert setting mode

**Comment by grzeg1** [comment]
+1 

many of the settings are really 'corner case' or super-advanced - like 'Running sport' - would anyone change it?

Complementary idea: remove settings that nobody is using:
- if nobody is using it in online version (active account)
- and we're not using it ;)
- mark it as 'deprecated' = comment as 'deprecated' in user interface
- if nobody using local version cries
- remove it in the next version
Unnecessary options=unnecessary code paths to test & more code & more complicated code

**Comment by laufhannes** [comment]
'Mainsport', 'Runningsport', 'Competition type' and 'Longjog type' could be moved to sports/types settings. 

But all other options are due to a request or personal preference some time ago. I don't see any option that's not used. (except for 'vdot formula')

I'd just prefer a clearer output for configuration, especially complete pages for each category instead of a combined form. In each of these pages one could add a (by default hidden) section for expert settings, group settings (e.g. 'activity view' is getting too big) and add notes and explanations instead of putting them into tooltips.

**Comment by mipapo** [comment]
I like the discussions today ;)
Like @laufhannes I think the most variables are used (sometimes maybe just some users, but I don't see that we should remove this variables)

The normal/expert mode was requested several times through the survey. Currently the initial hurdle is definitely to high for "normal" runners.

(Will create a similiar ticket like this for configure sport)

**Comment by mipapo** [comment]
I think we can close this ticket as it's a flowing proccess. With the refactoring of all configuration form we are looking how important a setting is and how often it's really used.
