### ISSUE TITLE
Endomondo tcx file issues

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1404]
- [ ] Detect pauses (like runtastic parser)
- [x] correct the pace?

https://www.dropbox.com/s/xelum8ddq2pzi42/2015-06-29_Running-endomondo.tcx?dl=0

**Comment by grzeg1** [comment]
Seems Endomondo is generating wrong TCX files on purpose. That's the reason I stopped using it at the time I did not have a GPS watch. I was a premium user at that time and asked many times for a fix. No results. Switched to sportstracklive.com app and the data was correct ever since. I was still using Endomondo as a platform, but with manual workout import. If you want to verify, import exported file back into Endomondo.

**Comment by mipapo** [comment]
I did ;) Really ugly. 
Just added this - maybe we could try to cleanup the file. But it has no priority

**Comment by laufhannes** [comment]
The pace will be correctly calculated as soon as the `feature/removePaceArray`-branch is merged into master.

**Comment by laufhannes** [comment]
And I don't see an easy way to detect if this file is from Endomondo. Everything works fine if the user deactivates our detection of pauses and further improvements will come with #913.
