### ISSUE TITLE
weather data: option "night"

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1447]
"Bei den Wetterdaten würde ich anregen, als zusätzliche Option "Nacht" anzubieten. Dies am besten in Kombination mit den bestehenden Wetterlagen, also z. B. Nacht + Regen, Nacht + Schnee, ..."
(idea via mail)

**Comment by laufhannes** [comment]
'Night' could be detected automatically and saved as an additional boolean field, so that it's independent from chosen weather. I'd define 'Night' as 'at least 50% of the activity between sunset and sunrise'.

```php
$timepoint = $Activity->timestamp() + 0.5 * $Activity->duration();
$isAfterSunset = $timepoint > date_sunset($timepoint, SUNFUNCS_RET_TIMESTAMP, $latitude, $longitude, $zenith, $gmt_offset);
$isBeforeSunrise = $timepoint < date_sunrise($timepoint, SUNFUNCS_RET_TIMESTAMP, $latitude, $longitude, $zenith, $gmt_offset);
$isNight = $isAfterSunset || $isBeforeSunrise;
```

(One may need to check for 'false' of date_sunset/date_sunrise, as the sun doesn't go done inside the arctic/antarctic circles)

**Comment by laufhannes** [comment]
+1 via http://forum.runalyze.de/viewtopic.php?p=1132#p1132

**Comment by mipapo** [comment]
@laufhannes Never seen your comment with date_sunset / date_sunrise. 
- [ ] Boolean value field for night
- [ ] Refactor-Script (Oh nooo :D) for checking all existing activities
- [ ] Plugin Trainings times (night times) should be based on the new field
- [ ] Night should be added to plugin Weather analysis
