### ISSUE TITLE
Inconsistent offset recognation

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1785]
Related to #1779
Timezone offset in training object is null for imported TCX files (`TrainingObject->setTimezoneOffset` is only called for FITLOG files). When saving to database, it's filled out by the inserter. Inserter does `TimezoneLookup` and fills in timezone inferred from location, not from original file. This is inconsistent so it's a bug.

**Comment by mipapo** [comment]
fortunately it's not that important that we have to publish 2.5.1 at once

**Comment by laufhannes** [comment]
TCX files contain in most cases utc time strings although these files are in another timezone. It would be wrong to always use an offset of 0 for these files. "null" means that the offset is unknown. That's not a bug. It's not a wrong offset - it's just no offset.

**Comment by laufhannes** [comment]
This will become even less important with #1781. (Not even mentioning that the offset is not used anywhere so far)

**Comment by grzeg1** [comment]
You said before that if TCX file contains timestamps with offset, the offset will be respected (I don't like this, but I understand your explanation). But in reality the offset is not respected in all places. Activity timestamp in the import form is calculated with offset from file (timezone from file is respected), but the offset saved to database is calculated from start point location (timezone from file is ignored). That's why I call it inconsistent => a bug, not enhancement.

**Comment by laufhannes** [comment]
Okay, now I get your point.

**Comment by grzeg1** [comment]
Cool ;)

**Comment by grzeg1** [comment]
I've looked at your commit and can't understand a few things. Can you explain how it works now?
It seems to me (maybe I'm mistaken) that:
- for Zulu timezone the offset&timestamp are calculated based on server time zone, not user time zone, not activity location - exactly like before timezones were introduced
- timezone detection based on activity location is never used

IMHO the desired way for the app to work would be:
- determine timestamp&offset when uploading the file based on activity location
- if location not available, use offset from user's time zone
- show timestamp&offset in edit form so user can change them
- save timestamp&offset to database along with other activity data when user clicks 'Save' button

**Comment by laufhannes** [comment]
Well, as it's only a bugfix for v2.5.1, it only fixes the mentioned inconsistency between the used and the saved offset. Now, every time the activity's timestamp is set, the offset is set as well.

> for Zulu timezone the offset&timestamp are calculated based on server time zone, not user time zone

The user time zone is used as server time zone: [Frontend::initTimezone()](https://github.com/Runalyze/Runalyze/blob/support/2.5.x/inc/class.Frontend.php#L112-L115)

> timezone detection based on activity location is never used

... as before this fix. It was only used to set (an inconsistent) offset. 
I totally agree that the location should be used whenever available. That's what #1782 is for and it's marked as a *must* ticket for v2.6.

---

> show timestamp&offset in edit form so user can change them

I'm not sure if this will bring benefits rather than new questions. *What is an offset?* (people know timezones, but do they know their current offset?) *Why can't I choose a timezone?* *Is the offset already added to the time?* - yes, looking at some other support questions, these will definitely arise, but the benefit is very small: The offset is not used anywhere and only saved for - *sick!* - consistency ;)
Feel free to add an issue for this. I probably won't put a veto on it, but I personally will not spend time on implementing it, as there's so much stuff around that I'd love to see in Runalyze.

**Comment by grzeg1** [comment]
When I said offset I did not mean displaying it as an integer value but rather as timezone dropdown.
So e.g you go to London for a marathon and get the right timestamp even though your main timezone is Berlin and the TCX file you use is, as usually, in Zulu timezone.
