### ISSUE TITLE
Average in weekly/monthly chart is wrong

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1928]
It shows the average of the current year or month?
When I choose another time range it should show the corresponding average and not the current one

**Comment by laufhannes** [comment]
As stated in the info text below:

> _Goal and average are based on current basic endurance calculations._

That's mainly relevant for the goal*, but the average is calculated based on basic endurance's percentage for weekly kilometer as well (which is equal to the average of the last 26 weeks by default).

 - **Option A**: Remove the coupling to basic endurance and just show the average.
   - imho there's no need to show the 'normal' average
 - **Option B**: Show these thresholds only for last 6/12 months and use '_current average_' as label.

\* We should use _target_ instead of _goal_.

---

In addition: Average and target are always shown in kilometer, even if the plot uses time for y-axis. (And that's a real bug, while the above things are 'only' confusing.)

**Comment by mipapo** [comment]
I prefer Option A

> In addition: Average and target are always shown in kilometer, even if the plot uses time for y-axis. (And that's a real bug, while the above things are 'only' confusing.)
Refactor with d3js :P
