### ISSUE TITLE
Nice date exception in trainings form

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1934]
When you type e.g. "1r.06.2016" (invalid date) there should be no exception like
"GIVEN TIMESTAMP MUST BE NUMERIC." but a form "error" to point to the incorrect date

**Comment by laufhannes** [comment]
This bug exists since switching to local timestamps. [FormularInputUTCDayAndDaytime](https://github.com/Runalyze/Runalyze/blob/ef96c1ec03fe8373f3275047a922e7304ce504c0/inc/html/formular/class.FormularInputUTCDayAndDaytime.php#L36) does not fetch validation failures of [FormularValueParser::validateDate()](https://github.com/Runalyze/Runalyze/blob/9b75a03df76405c035bea52285d7c05b3328c122/inc/html/formular/class.FormularValueParser.php#L343) which is called in `parent::validate()`. (It does not even return a value at all)

Current method:
```php
	public function validate() {
		parent::validate();

		$_POST[$this->name] = LocalTime::fromServerTime($_POST[$this->name])->getTimestamp();
	}
```

Soluation:
```php
	public function validate() {
		$result = parent::validate();

		if (true === $result) { // An additional try-catch-block can be added here
			$_POST[$this->name] = LocalTime::fromServerTime($_POST[$this->name])->getTimestamp();
		}

		return $result;
	}
```
