### ISSUE TITLE
Weekly chart wrong

### ISSUE THREAD

**Issue by Celphor** [Runalyze/Runalyze#1941]
Hi,

the weekly chart is wrong. Hope you can see it from the picture attached.
Last week was 35.12 km and is displayed as 40.43, and this week is show as 25.14 while the truth is 5.94 km.
The rest is correct.
Yesterday I switched from week start monday to sunday, because I start a structured training now and sunday fits better as week start. 
If I switch back the chart is ok! Did all cache and DB refreshes, no change. 

Applies to version 3.0.0

Greetings, Uli

![wochenstat](https://cloud.githubusercontent.com/assets/22246844/18618407/694cf81e-7de6-11e6-8d1a-bd157e115fa6.jpg)

**Comment by laufhannes** [comment]
We have to further investigate that one. According to https://github.com/Runalyze/Runalyze/blob/ef96c1ec03fe8373f3275047a922e7304ce504c0/inc/draw/class.PlotWeekSumData.php#L84-L90 the week start should be respected correctly.

**Comment by Celphor** [comment]
Applies only to 12 month view, 6 month and others are ok

**Comment by Celphor** [comment]
Today  is 18.09.2016. 
Where Criteria on training.time is >=13.09.15. It seems that data from september 2015 is merged into september 2016 ;-)

**Comment by Celphor** [comment]
Ok, the buggy function seems to be:

` protected function beginningOfTimerange() {
                if (date('w') == 0) {
                        return LocalTime::fromString($this->WeekStart->firstDayOfWeekForStrtotime()." -".$this->timerEnd." weeks 00:00")->getTimestamp();
                }

                return LocalTime::fromString($this->WeekStart->firstDayOfWeekForStrtotime()." -".($this->timerEnd - 1)." weeks 00:00")->getTimestamp();
        }
in inc/draw/class.PlotWeekSumData.php

It is going back too far (see above)

**Comment by Celphor** [comment]
Data comes from DB via a "group by" week number (calculated in function timer()). Weeks from current month in previous year (not shown in the diagram) add up to the current month of current year.

**Comment by mipapo** [comment]
@Celphor You know that there is an edit button for your own comments ;)

**Comment by laufhannes** [comment]
Can you check whether weekly kilometers are still wrong? As it's now Monday, I guess that the bug is not visible anymore. Still, I'm unsure which part of `beginningOfTimerange` causes the bug.

If it's Sunday *and* week start is set to Sunday, the current day belongs to the 'upcoming' week while php and `strtotime` will probably think it's still part of the 'last' week.

My current guess is that the if clause should be
```php
if ($this->WeekStart->isSunday() && date('w') != 0)
```
but that has to be verified on a Monday *and* on a Sunday for both possible week starts (and with making sure that there are kilometers on respective days that could conflict).

**Comment by Celphor** [comment]
@mipapo Ok, I won't flood your mailbox anymore. Seems I'm a Facebook victim ;-)

@laufhannes Indeed, today everything looks fine. Also switching week start to monday displays the correct chart.

**Comment by laufhannes** [comment]
Damn it. I forgot to have a look at it yesterday whether it's correct on Sundays now as well.

**Comment by Celphor** [comment]
Nicht vergessen, morgen ist Sonntag ;-)

**Comment by laufhannes** [comment]
Ich habe dieses Mal tatsächlich eine Notiz im Kalender ;)

**Comment by laufhannes** [comment]
It seems that this does not work so far. The problem is that MySQL handles week numbers differently as we are doing in php. According to ISO 8601 (which also defines Monday as the first day of week) week 01 is the week with the years' first Thursday in it. For Monday as week start this is equivalent to 'the first week with 4 or more days of it in January'. MySQL seems to use this second definition for its week numbers when using `WEEK(..., 6)`.

That causes MySQL to let Sun, 04.10.2015 - 10.10.2015 be week 40 while with Monday as week start Mon, 05.10.2015 - 11.10.2015 is week 41.

In addition, this currently causes an empty week for the beginning of January as php expects 2015 to have 53 weeks but MySQL returns at most 52.

We need to fix the week number by adding 1 (if php and MySQL have different week numbers - how to determine?) or by using `WEEK(DATE_ADD(FROM_UNIXTIME(`time`), INTERVAL 1 DAY),3)` instead.
