### ISSUE TITLE
Division by zero in Math/Derivative

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1952]
```
--- a/inc/core/Calculation/Math/Derivative.php
+++ b/inc/core/Calculation/Math/Derivative.php
@@ -30,7 +30,7 @@ class Derivative
         $ddx = [];
 
         for ($i = 1; $i < $num; ++$i) {
-            $ddx[] = ($y[$i] - $y[$i - 1]) / ($x[$i] - $x[$i - 1]);
+            $ddx[] = ($x[$i] == $x[$i - 1])?0:($y[$i] - $y[$i - 1]) / ($x[$i] - $x[$i - 1]);
         }
 
         array_unshift($ddx, $ddx[0]);
```

**Comment by laufhannes** [comment]
The derivative is not defined for `x_i-1 = x_i` and asymptotically it's rather infinity than zero.

Where does this input come from? Why are there two successive points with the same distance? (At least, I guess that it's thrown while trying to calculate the gradient profile?)

**Comment by grzeg1** [comment]
I guess it's because I'm using time as x-axis. It also means that for time as x-axis gradient calculation should be corrected and equal x values should be skipped.

**Comment by grzeg1** [comment]
Maths-wise you're 100% right.

**Comment by laufhannes** [comment]
The gradient calculation in https://github.com/Runalyze/Runalyze/blob/master/inc/core/Calculation/Route/Gradient.php always uses distance as 'x-values' (the calculation itself is completely independent from plotting the series).

However, this is something we 'gained' by not being restrictive for importing files so far. I clearly vote for 'no' to adapt algorithms like this one to support bad input data. If the given input data is not feasible for calculating a gradient an exception should be thrown. That's my point of view for creating a clean code base.

From the 'Show me as much as possible (even if it's not completely correct)' point of view ignoring bad values and using e.g. `null` can work. But this will cause further issues elsewhere and more and more lines of code to support this 'bad data'. How to handle `null` in average calculation? Can we assume that the plotting library will handle `null` correctly?

As we're not really near to v3.1 currently we don't need a quick&dirty fix. These are my suggestions:
 - \*`Math/Derivative` should throw an `InvalidArgumentException`
 - \*`Calculation/Route/Gradient` should check it's distance array and throw an `InvalidArgumentException`
 - gradient should not be added to plot if it throws an exception
 - we should prepare some general `InvalidActivityException` that can be thrown by the activity view
 - we should provide a tool to 'fix' activities (fix time or distance array; removing time series could be moved from edit form to this tool as well)
 - the importer should be more restrictive (add more checks like the one in https://github.com/Runalyze/Runalyze/commit/d30b8bd57b35251e13fd3f4c72ca11b1acca5d07)

\* Instead of throwing an exception I can agree with using previous gradient if files with equal distance points are common. We need to check files from 'bad' devices (mobile apps like Runkepper, Endomondo and co) to verify this.

**Comment by grzeg1** [comment]
It has nothing to do with 'bad' files. I just stopped a few times so the distance was not increasing....

**Comment by laufhannes** [comment]
Okay. I personally prefer to exclude such stops from the activity but I can accept if other people handle that differently (and maybe bad devices like some apps will produce such distance arrays as well).

I guess, in general, elevation values `$y[$i]` and `$y[$i - 1]` are equal for these situations and gradient should be zero then.  So, how about

```php
for ($i = 1; $i < $num; ++$i) {
    $deltaY = $y[$i] - $y[$i - 1];
    $deltaX = $x[$i] - $x[$i - 1];

    if (0 == $deltaY || (0 == $deltaX && 1 == $i)) {
        $ddx[] = 0;
    } elseif (0 == $deltaX) {
        $ddx[] = $ddx[$i - 2];
    } else {
        $ddx[] = $deltaY / $deltaX;
    }
}
```

**Comment by grzeg1** [comment]
I guess that would be ok. Although for legibility's sake I'd prefer
```
        for ($i = 1; $i < $num; ++$i) {
            $deltaX = $x[$i] - $x[$i - 1];
            $deltaY = $y[$i] - $y[$i - 1];

            if ($deltaX > 0) {
                $ddx[] = $deltaY / $deltaX;
            } elseif ($i > 1) {
                $ddx[] = $ddx[$i - 2];
            } else {
                $ddx[] = 0;
            }
        }
```
