### ISSUE TITLE
Paces wrong in subsegment analyze

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1987]
seems like a bug in Twig template - why not just use:
```php
<td>{{ this.tableCell(pace|round|date('i:s'), "/km") }}</td>
```

**Comment by mipapo** [comment]
Don't forget to ignore the timezone if you're using `date`
`<td>{{ this.tableCell(pace|round|date('i:s', false), "/km") }}</td>`

**Comment by grzeg1** [comment]
I don't know Twig at all ;). What I posted above was what worked for me, I just don't understand why the pace in was multiplied by 60 and shown as hours:minutes

**Comment by laufhannes** [comment]
It was shown in `G:i` because there's no format for *minutes without leading 0* and for me it's quite unusual to show paces as e.g. `04:36` and not `4:36`.

However, since https://github.com/Runalyze/Runalyze/commit/016067a630999f3459d54b7aab757a086cf8cdc7 the ugly workaround of using `date()` is removed and [CoreBundle/Twig/DisplayablePace](https://github.com/Runalyze/Runalyze/blob/016067a630999f3459d54b7aab757a086cf8cdc7/src/CoreBundle/Twig/DisplayablePace.php) is used instead.

Do paces look fine for you now or is there still any issue?

**Comment by grzeg1** [comment]
Seems fine now.
