### ISSUE TITLE
Fetching weather data seems to use incorrect timezone 

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#2130]
At least for darksky

**Comment by mipapo** [comment]
https://github.com/Runalyze/Runalyze/blob/7c3aa1d64530bdf10a61364d123111ff840788a0/inc/training/class.TrainingObject.php#L69
https://darksky.net/dev/docs/faq#timezones
I think for the correct timezone it should be
`$Location->setTimestamp((new DateTime($_GET['date']))->getTimestamp());`
But I'm not sure if it would be correct for the openWeatherMap API.


(const TIME_PRECISION = 3600; should be adjusted to 1800)

**Comment by mipapo** [comment]
I think there is another bug in the openStreetMap API. 
I even get weather data for that activity,which was on 11, 2017 @ 4:36
[1671794846.zip](https://github.com/Runalyze/Runalyze/files/937531/1671794846.zip)

**Comment by laufhannes** [comment]
We should adjust `Runalyze\Data\Weather\Location` to hold a complete `DateTime` object instead of using a single timestamp. This way, forecast strategies can respect the complete `DateTime` object. The current method `setTimestamp()` is irritating as it's unclear whether our 'local timestamp' or an official timestamp is used.
