### ISSUE TITLE
Multi editor: form's java script is not evaluated on initial load

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#2152]
via https://forum.runalyze.com/viewtopic.php?f=47&t=735

**Comment by laufhannes** [comment]
It seems that java script code within `lib/jquery.form.include.php` is not evaluated when loading the multi editor (after searching for specific activities). Can't fix so far ...

**Comment by laufhannes** [comment]
Instead of what I've tried so far, it's probably enough to use the correct selector in https://github.com/Runalyze/Runalyze/blob/master/lib/runalyze.lib.feature.js#L227, where it's still `$("form.ajax input[name=send_to_multiEditor]:checked")` but the correct name in our search form is `send-to-multi-editor`.
