### ISSUE TITLE
GPX importer: pauses between trkseg are not recognized

### ISSUE THREAD

**Issue by jluttine** [Runalyze/Runalyze#2194]
I have a GPX file which contains a gap because I forgot to turn tracking back on after having a short break. So i moved many kilometers until I remembered to switch it back on. This break period causes weird things in Runalyze. It thinks I've moved those many kilometers in a very short time and thus thinks I've had an incredible speed of 1500km/h or so. Doesn't runalyze use the timestamps from the GPX file? From timestamps it is obvious that it took about an hour between the two GPS measurements. Using that time period and the moved distance would give some reasonable speed estimate. Another option would be to consider each `trkseg` separately without connecting them, so an activity can consist of multiple disjoint tracks. Not sure which one would be the correct/best way if either, but in any case the current behaviour seems like a bug to me.

Here are the relevant lines from my GPX:

```
      <trkpt lat="67.694822503253818" lon="24.368220688775182">
        <ele>272.5</ele>
        <time>2010-04-02T14:10:10.748+02:00</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="67.683182302862406" lon="24.207767676562071">
        <ele>350</ele>
        <time>2010-04-02T15:13:10.834+02:00</time>
      </trkpt>
```

My full GPX file is available here: https://ufile.io/12vi7

**Comment by laufhannes** [comment]
Our credo is: *bullshit in, bullshit out*

GPX format is one of the worst formats. There is no official way how to mark pauses and so on. Looking at our code, it seems that automatic pause detection is disabled between tow track segments (`<trkseg>`) - don't ask me why. One could try to adjust that - I don't know how our unit tests will react.

For a quick fix: try to remove `</trkseg><trkseg>` from those lines.

Short story: I'm sick of fixing our parsers because of little issues in gpx or tcx files, just because many devices handle all that stuff differently. There are some related issues:
 - #1576 - Pass-through filter for activities (files with inconsistent data should be rejected)
 - #913 - Importer: use/define 'AutoPause' (let the user define how pause detection should work)
 - #1352 - Edit/Create GPS route/data by hand (let the user cut/split/edit all trackdata arrays)

**Comment by jluttine** [comment]
Thanks for the workaround! Removing `</trkseg><trkseg>` indeed made the result much more reasonable.
