### ISSUE TITLE
Equipment for all sport types

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#581]
Equipment must be available for all sport types. Running shoes and clothes have to be migrated to a new database structure.

Users should be able to define their own categories/types of equipment, e.g. bikes. Each type should have its own predefined lifetime.

**equipment_type**
 - `id`
 - `name`
 - `input` (`select | checkbox`)
 - `max_km`
 - `max_time`
 - `accountid`

**equipment**
 - `id`
 - `name`
 - `typeid`
 - `notes` (current weight of shoes has to go here)
 - `distance`
 - `time`
 - `additional_km`
 - `date_start`
 - `date_end` (instead of inuse)
 - `accountid`

**equipment_sport**
 - `sportid`
 - `equipment_typeid`

**activity_equipment**
 - `activityid`
 - `equipmentid`

TODO:
 - [x] save / update equipment from edit form
 - [x] ~~find a way to represent each type for its own in the dataset~~ see #1484
 - [x] json backup/import
 - [x] Search function
 - [x] Plugin (Order limit km/time)
 - [x] Cleanup / Recalculate Equipment

**Comment by laufhannes** [comment]
+1 from a user

**Comment by mipapo** [comment]
max_km & max_time vielleicht auch in der Tabelle equipment? Und von _type werden die Felder nur als Standard übernommen?

**Comment by laufhannes** [comment]
I'd keep that at `equipment_type`.

 - If one wants to have a maximal lifetime for an equipment without group -> just create a group for it
 - cases where one believes in different lifetimes for objects within the same group are probably only opinion-based and I don't see a large drawback by assuming the same lifetime for all of them
 - assume a user used 1.000 km as maximal distance for running shoes and changes his mind -> he'd have to change the value for every shoe instead of just changing the group value

**Comment by mipapo** [comment]
`select * from runalyze_equipment eq LEFT JOIN runalyze_equipment_type eqt ON eq.typeid = eqt.id LEFT JOIN runalyze_equipment_sport eqs ON eqt.id = eqs.equipment_typeid;`

**Comment by mdosch** [comment]
If you already restructure the database you may consider using more generic names. As I added my MTB shoes to the database it's a little bit weird that they appear in training view as "running shoes". :)
A bike database would also be nice. :)

**Comment by laufhannes** [comment]
There'll be a new table for `equipment_type`: https://github.com/Runalyze/Runalyze/blob/feature/equipment/inc/install/feature-equipment.sql
